variable "aws_region" {
  description = "AWS region to deploy resources in."
  type        = string
  default     = "us-east-2"
}

variable "project_name" {
  description = "Project name prefix for resources."
  type        = string
  default     = "microdemo"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.0.0.0/16"
}

variable "public_subnet_cidr" {
  description = "CIDR block for the public subnet."
  type        = string
  default     = "10.0.1.0/24"
}

variable "public_subnet_cidrs" {
  description = "List of CIDR blocks for the public subnets."
  type        = list(string)
  default     = ["10.0.1.0/24", "10.0.2.0/24"]
}

variable "s3_bucket_name" {
  description = "Name for the S3 bucket (optional, autogenerated if not set)."
  type        = string
  default     = null
}

variable "sqs_queue_name" {
  description = "Name for the SQS queue (optional, autogenerated if not set)."
  type        = string
  default     = null
}

variable "ssm_token_name" {
  description = "Name for the SSM parameter storing the API token"
  type        = string
  default     = "/microservices-demo/api-token"
}

variable "ssm_token_value" {
  description = "Value for the API token stored in SSM (use random.password for secure generation)"
  type        = string
  default     = null # Will be generated securely using random provider
  sensitive   = true
}

variable "api_receiver_image" {
  description = "Docker image for the API receiver"
  type        = string
  default     = "" # empty fallback — we'll set real value in locals
}

variable "api_receiver_port" {
  description = "Port for the API receiver microservice."
  type        = number
  default     = 8080
}

variable "sqs_worker_image" {
  description = "Docker image for the SQS worker"
  type        = string
  default     = ""
}

variable "sqs_worker_port" {
  description = "Port for the SQS worker microservice."
  type        = number
  default     = 8080
}
